# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100)),
                ('article_desc', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myarticle.Signup')),
            ],
        ),
    ]
